#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo 'Formatting code with csharpier...' 
dotnet husky run --name "Run csharpier"

echo 'Run dotnet restore'
dotnet husky run --name "Run dotnet Restore"

echo 'Run dotnet build'
dotnet husky run --name "Run dotnet build"